# -*- coding: utf-8 -*-
"""Hands-on 1: Implementación de Autómatas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wAz1W9VILLHnXeKTRgDRTmnJtYeFrnPE

# **Autómatas**

# Autómata 1: Validación de Cadenas Alfabéticas

Este autómata valida cadenas compuestas  ́unicamente por letras mayúsculas y
"""

def validate_alpha(s):
    return s.isalpha()

# Pruebas
test_cases = ["HelloWorld", "123Hello", "Python", "Code123", "Rosa", "R&S"]

for test in test_cases:
    if validate_alpha(test):
        print(f"'{test}' → Cadena válida.")
    else:
        print(f"'{test}' → Cadena inválida.")

"""# Autómata 2: Validación de Números Reales

Este autómata valida números reales con signo opcional y punto decimal.

"""

def validate_real(s):
    try:
        float(s)  # Convierte la cadena a float
        return True
    except ValueError:
        return False

# Pruebas
test_cases = ["-123.456", "3.14", "00123", "+456", "12.34.56"]

for test in test_cases:
    if validate_real(test):
        print(f"'{test}' → Número válido.")
    else:
        print(f"'{test}' → Número inválido.")

"""# Autómata 3: Validación de Sentencias Selectivas
Este autómata valida sentencias selectivas simples como if-else.

"""

def validate_if_else(s):
    return "if" in s and "else" in s

# Pruebas
test_cases = [
    "if x > 0: pass else: pass",
    "if (x > 0) { } else { }",
    "if x > 0: pass",
    "else: pass"
]

for test in test_cases:
    if validate_if_else(test):
        print(f"'{test}' → Sentencia válida.")
    else:
        print(f"'{test}' → Sentencia inválida.")